/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://xshymwiexzhyncdmoze4gvqjhu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-b7fiwsydonbgteptypis4jroku",
    "aws_content_delivery_bucket": "integragitex2021-20211007221839-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://integragitex2021-20211007221839-hostingbucket-dev.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
